# Application Configuration
database_url=postgres://postgres:password@localhost:5432/item_service?sslmode=disable
grpc_port=50051

# Migration Configuration
liquibase_changelog=db/changelog-master.yaml
