# Application Configuration
database_url=postgres://postgres:password@localhost:5432/item_service?sslmode=disable
database_reader_url=postgres://postgres:password@localhost:5432/item_service?sslmode=disable
database_writer_url=postgres://postgres:password@localhost:5432/item_service?sslmode=disable
grpc_port=50051
http_port=8080

# Migration Configuration
liquibase_changelog=db/changelog-master.yaml
